"""add portfolio id

Revision ID: 007d42b2ff11
Revises: d6b83983d025
Create Date: 2021-06-07 14:45:04.034754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007d42b2ff11'
down_revision = 'd6b83983d025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('portfolio_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'run', 'portfolio', ['portfolio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'run', type_='foreignkey')
    op.drop_column('run', 'portfolio_id')
    # ### end Alembic commands ###
