"""add asset portfolio

Revision ID: 29a772b79352
Revises: 3f8607e17523
Create Date: 2021-05-22 14:45:05.858934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a772b79352'
down_revision = '3f8607e17523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_asset_broker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('asset_broker_pair_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_broker_pair_id'], ['asset_broker_pair.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_broker_pair_id', 'portfolio_id', name='_asset_broker_pair_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_asset_broker')
    # ### end Alembic commands ###
