"""add qty for portfolio_asset

Revision ID: 56a18f01f13c
Revises: 5878b3f43d07
Create Date: 2021-06-03 09:44:32.389050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56a18f01f13c'
down_revision = '5878b3f43d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_asset_broker', sa.Column('qty', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_asset_broker', 'qty')
    # ### end Alembic commands ###
