"""enum

Revision ID: 8d2b19d49fa6
Revises: 5d5e2a2da42f
Create Date: 2021-06-07 18:06:35.199168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d2b19d49fa6'
down_revision = '5d5e2a2da42f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'side',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('buy', 'sell', name='transactionenum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'side',
               existing_type=sa.Enum('buy', 'sell', name='transactionenum'),
               type_=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
