"""add quote_balance in portfolio

Revision ID: 959143f3533f
Revises: 56a18f01f13c
Create Date: 2021-06-04 09:36:55.666521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '959143f3533f'
down_revision = '56a18f01f13c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('quote_asset_balance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio', 'quote_asset_balance')
    # ### end Alembic commands ###
