"""add asset_broker_pair

Revision ID: b2f9a070cb5f
Revises: e2ad370c0673
Create Date: 2021-05-09 19:18:03.239946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2f9a070cb5f'
down_revision = 'e2ad370c0673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_broker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['broker_id'], ['broker.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_id', 'asset_id', name='_asset_broker_uc')
    )
    op.create_index(op.f('ix_asset_broker_id'), 'asset_broker', ['id'], unique=False)
    op.create_table('asset_broker_pair',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_id', sa.Integer(), nullable=True),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['base_id'], ['asset_broker.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['asset_broker.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_id', 'quote_id', name='_base_quote_uc')
    )
    op.create_index(op.f('ix_asset_broker_pair_id'), 'asset_broker_pair', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_broker_pair_id'), table_name='asset_broker_pair')
    op.drop_table('asset_broker_pair')
    op.drop_index(op.f('ix_asset_broker_id'), table_name='asset_broker')
    op.drop_table('asset_broker')
    # ### end Alembic commands ###
