"""add portfolio

Revision ID: c9d4ee11e632
Revises: 369501290d20
Create Date: 2021-05-18 07:44:10.471443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d4ee11e632'
down_revision = '369501290d20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
