"""add asset model

Revision ID: e2ad370c0673
Revises: 37b826c97024
Create Date: 2021-05-09 19:03:46.055220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2ad370c0673'
down_revision = '37b826c97024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('cmc_rank', sa.Integer(), nullable=True),
    sa.Column('circulating_supply', sa.Float(), nullable=True),
    sa.Column('total_supply', sa.Float(), nullable=True),
    sa.Column('cmc_id', sa.Integer(), nullable=True),
    sa.Column('sign', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_cmc_id'), 'asset', ['cmc_id'], unique=True)
    op.create_index(op.f('ix_asset_cmc_rank'), 'asset', ['cmc_rank'], unique=False)
    op.create_index(op.f('ix_asset_id'), 'asset', ['id'], unique=False)
    op.create_index(op.f('ix_asset_name'), 'asset', ['name'], unique=False)
    op.create_index(op.f('ix_asset_slug'), 'asset', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_slug'), table_name='asset')
    op.drop_index(op.f('ix_asset_name'), table_name='asset')
    op.drop_index(op.f('ix_asset_id'), table_name='asset')
    op.drop_index(op.f('ix_asset_cmc_rank'), table_name='asset')
    op.drop_index(op.f('ix_asset_cmc_id'), table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
