"""add Optimizer

Revision ID: e47b53c47844
Revises: 3260451ff662
Create Date: 2021-05-29 15:43:42.974420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47b53c47844'
down_revision = '3260451ff662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimizer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('portfolio', sa.Column('optimizer_id', sa.Integer(), nullable=True))
    op.add_column('portfolio', sa.Column('risk_free', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'portfolio', 'optimizer', ['optimizer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portfolio', type_='foreignkey')
    op.drop_column('portfolio', 'risk_free')
    op.drop_column('portfolio', 'optimizer_id')
    op.drop_table('optimizer')
    # ### end Alembic commands ###
