language: python
cache: pip
python:
- '3.7'
install:
- pip install awscli
- pip install aws-sam-cli
jobs:
  include:
  - stage: init master
    skip_cleanup: true
    before_install:
    - bash ./scripts/aws_config.sh
    if: branch = master
    script:
    - aws cloudformation deploy --template-file ./templates/00-infra.yml --stack-name
      glaedis-infra-$TRAVIS_BRANCH --region=$AWS_DEFAULT_REGION --capabilities CAPABILITY_IAM
      --parameter-overrides RootDomain=$DOMAIN RegionalCertArn=$REGIONAL_CERT HostedZoneId=$HOSTED_ZONE_ID
      CloudFrontCertArn=$CLOUDFRONT_CERT EmailAddress=$EMAIL EnvironmentName=$TRAVIS_BRANCH
      --no-fail-on-empty-changeset
  - stage: init dev
    skip_cleanup: true
    before_install:
    - bash ./scripts/aws_config.sh
    if: branch = dev
    script:
    - aws cloudformation deploy --template-file ./templates/00-infra.yml --stack-name
      glaedis-infra-$TRAVIS_BRANCH --region=$AWS_DEFAULT_REGION --capabilities CAPABILITY_IAM
      --parameter-overrides RootDomain=$DEV_DOMAIN RegionalCertArn=$DEV_REGIONAL_CERT
      HostedZoneId=$DEV_HOSTED_ZONE_ID CloudFrontCertArn=$DEV_CLOUDFRONT_CERT EmailAddress=$EMAIL
      EnvironmentName=$TRAVIS_BRANCH --no-fail-on-empty-changeset
  - stage: architecture
    skip_cleanup: true
    if: branch IN (dev, master)
    before_install:
    - bash ./scripts/aws_config.sh
    script:
    - aws cloudformation deploy --template-file ./templates/01-vpc.yml --stack-name
      glaedis-vpc-$TRAVIS_BRANCH --parameter-overrides EnvironmentName=$TRAVIS_BRANCH
      --no-fail-on-empty-changeset
    - aws cloudformation deploy --template-file ./templates/02-tables.yml --stack-name
      glaedis-tables-$TRAVIS_BRANCH --parameter-overrides EnvironmentName=$TRAVIS_BRANCH
      --no-fail-on-empty-changeset
    - mkdir zip
    - zip -r -j zip/PostConfirmation.zip backend/PostConfirmation
    - aws s3 cp zip/PostConfirmation.zip s3://glaedis-backend-${TRAVIS_BRANCH}/
    - aws cloudformation deploy --template-file ./templates/03-cognito.yml --stack-name
      glaedis-cognito-$TRAVIS_BRANCH --region=eu-west-1 --capabilities CAPABILITY_NAMED_IAM
      --parameter-overrides EnvironmentName=$TRAVIS_BRANCH --no-fail-on-empty-changeset
    - zip -r -j zip/GenerateKey.zip backend/GenerateKey
    - aws s3 cp zip/GenerateKey.zip s3://glaedis-backend-${TRAVIS_BRANCH}/
    - zip -r -j zip/GetUser.zip backend/GetUser
    - aws s3 cp zip/GetUser.zip s3://glaedis-backend-${TRAVIS_BRANCH}/
    - aws cloudformation deploy --template-file ./templates/04-user-api.yml --stack-name
      glaedis-user-api-$TRAVIS_BRANCH --region=eu-west-1 --capabilities CAPABILITY_NAMED_IAM
      --parameter-overrides EnvironmentName=$TRAVIS_BRANCH --no-fail-on-empty-changeset
    - zip -r -j zip/TestKey.zip backend/TestKey
    - aws s3 cp zip/TestKey.zip s3://glaedis-backend-${TRAVIS_BRANCH}/
    - aws cloudformation deploy --template-file ./templates/05-test-api.yml --stack-name
      glaedis-test-api-$TRAVIS_BRANCH --region=eu-west-1 --capabilities CAPABILITY_NAMED_IAM
      --parameter-overrides EnvironmentName=$TRAVIS_BRANCH --no-fail-on-empty-changeset
    - aws cloudformation deploy --template-file ./templates/06-site.yml --stack-name
      glaedis-site-$TRAVIS_BRANCH --region=eu-west-1 --capabilities CAPABILITY_NAMED_IAM
      --parameter-overrides EnvironmentName=$TRAVIS_BRANCH --no-fail-on-empty-changeset
    - cd backend/App
    - sam valdiate
    - sam build --debug
    - sam package --s3-bucket glaedis-backend-${TRAVIS_BRANCH} --s3-prefix glaedis-app-api-${TRAVIS_BRANCH} --output-template-file out.yml --region eu-west-1
    - sam deploy --template-file out.yml --stack-name glaedis-app-api-$TRAVIS_BRANCH --region eu-west-1
      --no-fail-on-empty-changeset --capabilities CAPABILITY_IAM
    - cd ../..
  - stage: Deploy front prod
    skip_cleanup: true
    language: node_js
    node_js:
    - node
    cache: npm
    before_install:
    - export ROOT_DOMAIN=${DOMAIN}
    - bash ./scripts/aws_config.sh
    if: branch = master
    script:
    - bash ./scripts/generate-env-front.sh
    - cat ./frontend/.env
    - cd frontend
    - npm install
    - npm run build
    - aws s3 cp ./dist s3://www.${DOMAIN}/ --recursive
  - stage: Deploy front dev
    language: node_js
    node_js:
    - node
    cache: npm
    skip_cleanup: true
    before_install:
    - export ROOT_DOMAIN=${DEV_DOMAIN}
    - bash ./scripts/aws_config.sh
    if: branch = dev
    script:
    - bash ./scripts/generate-env-front.sh
    - cat ./frontend/.env
    - cd frontend
    - npm install
    - npm run build
    - aws s3 cp ./dist s3://www.${DEV_DOMAIN}/ --recursive
env:
  global:
  - AWS_DEFAULT_REGION=eu-west-1
  - DOMAIN=glaedis.com
  - DEV_DOMAIN=dev.glaedis.com
  - EMAIL=simon.pichon@outlook.fr
  - secure: zcAsOW8nmE1NCyVmSvFCvU740qh9MrSJ55H9OSroRaBfFbQ6oDBhZXWA5+lzpxu9KybG2hThL5l75IMkbR3LbMCnJnv0iBOtkFoJSBV4Hg5PtDns33l4MGPmDhDegNiDEuHMAMxBC0kgbwswW5VR2OuuegCj2OA5KGRI0qC5/Yo2v6DkhC3FKcRwMP4vccz7+JS++kcuHwTgLik6VnIGOBrIzbQjZPWIBPhq24qTVpZjDWnAsZuLt2Dj9dwR8qbyIhht7vam7ZWk/IBfLnEg6yvKcVSr8lJkfH4D5A8uajKifiw9YqYavlKhPIX/QmthV3Kteg5OaFW6gB50WJcsa2pgTIicE93ooPWa1SW0wGSyetCq/I73zXCqmtXBHgKVUcYbzy7pwKh2NkKz2B0wian/4sjuCGIeugC7n2PZOdH0mK/semNsqwuzQTDemkF/iS7PEqh2vUayJ523pSnFRnoJ/BZSfMkb17OFCt/jKwXJ6OGhJ7SMqVXeqXQTw75pSG1aPgAQ0ealtaLOKB3ZC+AehvD+fBIbCBHcS8WiT+xQcdQNHYqIR6l0z5NCeUGGs+tFM32p+qZ7vATWaXRQPGzilxG8NicM51Tlm7lQ6ZcKgA4msM8joTWEnOmttSmvP5jy2bIWKt5W5ce40j703IRufWMMW+0PsCCUqHbwtMY=
  - secure: UDH1UAXr2Yftj+G/LD9aWZdnG5GyYk/TilNqgJj8/bA0fCP4noSKPz9CRunlVKjblK7rXTdbJr1fciyeNIdE3ZoX9KJED/qNgQV8a808IVgKQ1hw75VvH6xNcNnB49bANmcb//AIgcnIz0jFi2q9zH1aNsedxYDvVhFaNa0Zaf20kiOM1wbxBAxL5L1Al//Qsh00fhrJ0+7kbdWBpuWvhZ5zJhjj6I+nhaH8tCI4lqDrhztQl6tBOzQXF1+/aTsmBmw0QgkXP/1QGfbTCifP87tJT3nHM0XQrCgfVTcyApsZ88oQbKhKPZ3X+b4XVM4Kx6mtVW6z7gI4MOBeJou5kO637T/YqjehO7dTzl58ay7gz4D3vUkJxzy8odPGXPRVbSLN2E6OV4mCzyZMSMIkkUfaGbmb+YsxT/3UpSEOx8VCF9FWeHFuDXDJsGAnpfisPnkGz4ZJY7HLnbgZOHUULEsdqiz4XIqYHva+OGtxvvAz4xkKIE6nGpeAb6ViXq6A+diJcAxEKkGNKMf1yymeKsAJ6j9ToAJfDYMWePxMUBgdjOtfv0EvfEWQaDTeLQNtOb71k8cweYHn3AuqAQZPfcwqY5By6OBDyEMSUzlSU7e4s5a35JSligjjmBccqytvmYE2W+ipUfWH5koFlZWvh22DXuS5QCrUUlBitxRfkD4=
  - secure: 0yoi8qa9wopQFCSSl8WqAU2rlcefDBlpFJtUI3U4Ql3isiakGucapZmYjkuSHztA7y5Ycudi3nGflHWlQk+pRrV+ci3Y8ZhGahP5CEIjbND/7OLCSaJxiO+aiZ2lWiRn7WVJu71/di69nUqrCFoqcZQes86CUa7b1AW0OmWdnuzU2Cg4PHxWPW356Zp+IYv9knQIfmhuAtrYKbRKdgK7fBFLoTbonnRVKBP9iPaEz61a++N/b5ZGcBk/+MSBfSdziKkS1V+m6+qzS4K2RzGN6kORpY+IxWqNKXd33CcEMj5brVBop0zcb8r+ynG/HROJCjOFwi2Lt29RwRK4DlumQxI3RN79IMUC/IlQfI6xcBrDlYTEHEExNwSEP8hGfQLG3vEuWAjbz+JaLlesAEHcCJpOGFrotpaw8I2KRzIXRlEEM3K1Eiq7qm2o5elOK78uh4rkrBgd0lIuK1TIHtBKQiuhrFadFXLqJouPyvDGRLUj/MU9KClnhaAhAik1EU5YuUi1ZaBE7JQRGTAsg3L+Arewhvhs5tmSmvyz+KKk3i5xY7L/Hl6WrHDrEWRaWeBcN2WOq1ReNVeUQQ4c/BATpvdM0WT52ySDR0BVoXqI8n1yjak/5b02Q55sicPndH5pt8Z5Mg+81kxlLCDoPEOx1Fjq2MEWatSEnsiie3RuCcA=
  - secure: V6tl7rJvNJz4k407BM8/zHbLruNsUJxPurardBgOT1v3+vBL3sd76POoX5WFC6lUX4CKsh3NYOlh3ZFbBOdFxR0tbljZWsJuXad+7uSB2KM4GK3luDSlRt/HkPsfOvmjqDBSXICpbR8d63xd0TrWeiMij2f3MSwGo3Qyf8Mjus4Chbnwc6EA5IAK0/l68N20UJfQcneFslZVdrfC8hYAoSTEnielUzAFKnFx5+Ixqd64pq3wK95oSXpaD0TGsO6d4TxAgiRKvTu2O3OW8qX3a06HZtn52WTLvc+ljgzLKl/gUncEPDomCa3mYBw7S/GTxCnLdTfmQMNYq+n4+MFpTRuyDHhcVYeEcrJ6oDdvkVcC3uLdpbcFGTkRA/QmKc2PKdU/hC9f+cDBEE3c+QxIwOuiSijEdreZ+HOaX1+/LJdoJCroCf6yLW+U3/rXJnAFR3vuDObgWeg3ut2RNIHOH3Hi7+o5o23yNqrlSZiWHPmFUG5uTgapSZ4NAWFnwUeV1QS9cTUAewSLD/n7d8viSNzZBfA5cxUGc+WV/jR9cMdMRPC5iEPuvwU0U1P+5+pR0aY4y5tv+fQzOq7Z469e5THNkNz3XBt8S3wxC10YN48Ro3mRAK4NaTeN0nEZtRPVQqec+GNtshcGO92/OsVc02SbZwIa+Tw2X+QwIxg8+cw=
  - secure: Mx3Cs1KZfN5ztz2X3sRJNBQ4Heo+0T5ZvOB6TeiFpxabPgW60RyXY9ewQMfiCU2t9PPHV633Sy5bMMJydaFeDA5MUBQ5Ck3GI54tIeSmZQxb7iPh7dxVh1g7IvFlrts6RmAZhT6xu5IaW9k3ltvQM+8Ayk4kXpdnXilSIwsN/ESdjxXUSux+IUWP3S6VmeJFx4tTDtXnklJoYz0YbxymylsCWxJaGm1EHs5dVjK9XJCFTGanfs5Qxsylrqn7lV2oNGE/P/TLWCOw9ycYdW7vOmv3E6J4Mcnhwtau9rSTO4E2XSr9pyGhk1uBjkhms1DWpsB2nmjBX0qqZVvK3Bo3Ci/QNlmvpGMLYySH7w7n1ijQ0mKUaz+WnKauc+F1eLlQxJjnTvBiN0q2kE0GbDMk6QnLo3Af4b4u/6gyPbwgR2tlosaa0XsyTXNxHQX6RS+O9Fw0hD2+5/LjKho0i8l9gX/qFsWrbcSJ01oMQQCy2uyfjSGNX0We7fb8p6n0RwlX0Ye+FghUz3G5dY36K6AYrNggVcIv6wdRgb6JenT6wST3oalfMqZt06sJz8TUXciuN4G/Z3JcGe6jj/GVOCjm7eofkcNhH/mRl6GY16c2Hcy8JDlCK/OdofD1VmCy6tARHAs5D5BAQs7cHfJWtmCgcjowTm61M87Q5TLRB7+oZXI=
  - secure: E47+1dJj3KBtC9uRkih/D4hKm3+OWrG1hOMh1XPikDWjK33iXt18yjCoPPgPObP6ZNmJS8vnIzFIfIu2Afp8zDdPlGg+WtEJ/JqriGi9nB4r33bcTCFN2ZmIrKG9SnwUPAvDclKrM1z9sHwrq7in5WSRY6nBlQAM2/xsRsajSp5jlofiaBxk7wKp2BPH4u8NI7x29tzWo32GBaSrl1bIyAEY6myRsmI6McfZkGOSM39WamarGX0ZpZ0byqCdLvfz32tX/UnjPrKxwYIJi5BLR/vkK38/Cq6ufJtaoluTdU5rxD2UYZ4X40O0ayWCYDzrZKU+gHh/FPin74dXxVUCAllLXrFnbf8OKL8/uwtx0URrRZ+QyotUW3eITMuAdxN5ceO5+NZYaRTPKkAj9WLpsSSL8XvFSMEQwkLWE/8BCc6YFUBgbwBXIXWPIWa6R/HhrmrzQPZdi43Yh40ujTnAkbITWkhN5hy6FNSAXn/RcCS578pwYHQSu5bWKepwy2nc4yRHtThMeS8JHXDt20PPOz3fJR6R++GJ11bwJ6r0oGS2ifaARYk3RNQ/MXUUp1nFREbLCNmocgCGCUH06ERtWqBvYdRrQR9BdF55i13xARDGjamGh9ZyO7rpaFTxbs+Ec861Row50OX3Y0+Z4A80Cz0Ty1yrib2YNQgMX8YdQO4=
  - secure: RzjeRQ8z0ZYqeHy5FlZxzrnDEWj6AB1wUHyRhYV5makBRQOenwsXk5TVkYXT7L5xBk/MGo4QmzzR/0+tbBWGStlzNSA2iw32AY6LLLZACIEHT/aojUfi4/dsZQLfARSXJBZRoNNN7K6m2cvuzpLO64TBI0yv3yNChYj5JE0xah/WR5oHYSRwGj3x1Y5nLxLy/QCq5NkjWxCfUUh2xfYMEBRvTnWW69oQEpRYthzD+irJDnRXFvSCVItKybfxGjtEv7C/1eb4t0T4eoMGDQ3V0c7fmL6jvkJLKCobxU1oUS7KWe3CoYBcX0n9geBO/hFyPJ9r2AICsQ5daR9PQtFwhTVIqXWqmHgvPzka0sjsoh4pcSAmvyLm6cSDzIz/q3olzkOHXiuU6LmKgoH8ybh4tF6IygpSaBVQ/2qFd6WfA2KFoEfVWJygZAarayU8axFj17p5UeVHYb4s8XiqGLxrt+hzMPWiwwY4vmW9xTm9LTZBl9/B26Y/Tdg2DmGEZvJSR0A4x1x5QTRQ7DjDFETBkhBch5uDxCGozNVf3+MEjE0gIOtdvlWvCHV9TstX0e1XgO8G66QRlrfjpQrt8c7ZN3mHfNyGrcwmPcTlH+4JhBCGPB7sroYLr3lcQUYCYZpd7wq22ycUt/Pxn1lrp+Ehf/lapFtvaZKi0XVlhwUz5u4=
  - secure: q+aDXA2I0D2qcpxlEAc+LwFkeMfkb9hoznk0o00vR1RiaGV9iva5e9iHltsMSq3J41F3B0+iuDhVfw6iomY5nQ2IEeGZeyAmBx5uciGqwMN8nAU8MpwiFJ2MWUYav1jUEhPgz/eeZQocTOb7Q0WUn6KJtt2qXLPonAB90IpRedudPwAnHnuSA8nPrpIxMHQs6EfLXXIFKePxET8Oi6eFf2Ouu9vlYHTQ0CcxVgnujJcXNw80dKkle3jzubdD6pR2OA0aPnlw2yGp7VPxy6LRyMJxlXo+vqeCcmr3tMIdFPlwEyiaDz8wcO3kivQMqjmMd7AtPGKZMf1HZfK6e7xq4dFVkSbOMgM5+wD1p6tkbhhbtHgPqbZGTbEhkgH0n2vgjbnPI3HiGfaiBhQ3UeHksaNCZWHsYI3k3er/kZ0+YUbX2vxwX455nf8sLDlthlSLgtu7CVVygCVXq8NLP46hcm60LotVA7OusGoWp7Yvv5WsZbKq5k4php8lqCmNlcQDO2K7Avp1bmeExeuUJZUJiM0M8PaFVzn2x/p5VypMgndxa5TAdS0W8F5Zsl4++smTL/q8issUnE4kNDd4Y28cBlnLGX4YOA3i2pdy12vmBU3UfZsl+dBUlB40RojeNV9dxTkmJOiko27oh+/WafsltZHSTHogntlK+rxHE/3+Vow=
