language: python
cache: pip
python:
- '3.7'
install:
- pip install awscli
- pip install aws-sam-cli
jobs:
  include:
  - stage: init master
    skip_cleanup: true
    before_install:
    - bash ./scripts/aws_config.sh
    if: branch = master
    script:
    - aws cloudformation deploy --template-file ./templates/00-infra.yml --stack-name
      glaedis-infra-$TRAVIS_BRANCH --region=$AWS_DEFAULT_REGION --capabilities CAPABILITY_IAM
      --parameter-overrides RootDomain=$DOMAIN RegionalCertArn=$REGIONAL_CERT HostedZoneId=$HOSTED_ZONE_ID
      CloudFrontCertArn=$CLOUDFRONT_CERT EmailAddress=$EMAIL EnvironmentName=$TRAVIS_BRANCH
      --no-fail-on-empty-changeset
  - stage: init dev
    skip_cleanup: true
    before_install:
    - bash ./scripts/aws_config.sh
    if: branch = dev
    script:
    - aws cloudformation deploy --template-file ./templates/00-infra.yml --stack-name
      glaedis-infra-$TRAVIS_BRANCH --region=$AWS_DEFAULT_REGION --capabilities CAPABILITY_IAM
      --parameter-overrides RootDomain=$DEV_DOMAIN RegionalCertArn=$DEV_REGIONAL_CERT
      HostedZoneId=$DEV_HOSTED_ZONE_ID CloudFrontCertArn=$DEV_CLOUDFRONT_CERT EmailAddress=$EMAIL
      EnvironmentName=$TRAVIS_BRANCH --no-fail-on-empty-changeset
  - stage: architecture
    skip_cleanup: true
    if: branch IN (dev, master)
    before_install:
    - bash ./scripts/aws_config.sh
    script:
    - aws cloudformation deploy --template-file ./templates/01-vpc.yml --stack-name
      glaedis-vpc-$TRAVIS_BRANCH --parameter-overrides EnvironmentName=$TRAVIS_BRANCH
      --no-fail-on-empty-changeset
    - aws cloudformation deploy --template-file ./templates/02-tables.yml --stack-name
      glaedis-tables-$TRAVIS_BRANCH --parameter-overrides EnvironmentName=$TRAVIS_BRANCH
      --no-fail-on-empty-changeset
    - mkdir zip
    - zip -r zip/PostConfirmation.zip backend/PostConfirmation
    - aws s3 cp zip/PostConfirmation.zip s3://glaedis-backend-${TRAVIS_BRANCH}/
    - aws cloudformation deploy --template-file ./templates/03-cognito.yml --stack-name
      glaedis-cognito-$TRAVIS_BRANCH --region=eu-west-1 --capabilities CAPABILITY_NAMED_IAM
      --parameter-overrides EnvironmentName=$TRAVIS_BRANCH --no-fail-on-empty-changeset
    - zip -r zip/GenerateKey.zip backend/GenerateKey
    - aws s3 cp zip/GenerateKey.zip s3://glaedis-backend-${TRAVIS_BRANCH}/
    - zip -r zip/GetUser.zip backend/GetUser
    - aws s3 cp zip/GetUser.zip s3://glaedis-backend-${TRAVIS_BRANCH}/
    - aws cloudformation deploy --template-file ./templates/04-user-api.yml --stack-name
      glaedis-user-api-$TRAVIS_BRANCH --region=eu-west-1 --capabilities CAPABILITY_NAMED_IAM
      --parameter-overrides EnvironmentName=$TRAVIS_BRANCH --no-fail-on-empty-changeset
    - zip -r zip/TestKey.zip backend/TestKey
    - aws s3 cp zip/TestKey.zip s3://glaedis-backend-${TRAVIS_BRANCH}/
    - aws cloudformation deploy --template-file ./templates/05-test-api.yml --stack-name
      glaedis-test-api-$TRAVIS_BRANCH --region=eu-west-1 --capabilities CAPABILITY_NAMED_IAM
      --parameter-overrides EnvironmentName=$TRAVIS_BRANCH --no-fail-on-empty-changeset
    - aws cloudformation deploy --template-file ./templates/06-site.yml --stack-name
      glaedis-site-$TRAVIS_BRANCH --region=eu-west-1 --capabilities CAPABILITY_NAMED_IAM
      --parameter-overrides EnvironmentName=$TRAVIS_BRANCH --no-fail-on-empty-changeset
  - stage: Deploy front prod
    skip_cleanup: true
    language: node_js
    node_js:
    - node
    cache: npm
    before_install:
    - export ROOT_DOMAIN=${DOMAIN}
    - bash ./scripts/aws_config.sh
    - export VUE_APP_COGNITO_USER_POOL_CLIENT_ID=$(aws cloudformation describe-stacks --stack-name glaedis-cognito-${TRAVIS_BRANCH} --query "Stacks[0].Outputs[?OutputKey=='CognitoUserPoolClientId'].OutputValue" --output text)
    - export VUE_APP_COGNITO_USER_POOL_ID=$(aws cloudformation describe-stacks --stack-name glaedis-cognito-${TRAVIS_BRANCH} --query "Stacks[0].Outputs[?OutputKey=='CognitoUserPoolId'].OutputValue" --output text)
    - echo ${VUE_APP_COGNITO_USER_POOL_CLIENT_ID}
    - echo $VUE_APP_COGNITO_USER_POOL_CLIENT_ID
    - echo ${VUE_APP_COGNITO_USER_POOL_ID}
    - echo $VUE_APP_COGNITO_USER_POOL_ID
    - bash ./scripts/generate-env-front.sh
    - cat ./frontend/.env
    if: branch = master
    script:
    - cd frontend
    - npm install
    - npm run build
    - aws s3 cp ./dist s3://www.${DOMAIN}/ --recursive
  - stage: Deploy front dev
    language: node_js
    node_js:
    - node
    cache: npm
    skip_cleanup: true
    before_install:
    - export ROOT_DOMAIN=${DEV_DOMAIN}
    - bash ./scripts/aws_config.sh
    - export VUE_APP_COGNITO_USER_POOL_CLIENT_ID=$(aws cloudformation describe-stacks --stack-name glaedis-cognito-${TRAVIS_BRANCH} --query "Stacks[0].Outputs[?OutputKey=='CognitoUserPoolClientId'].OutputValue" --output text)
    - export VUE_APP_COGNITO_USER_POOL_ID=$(aws cloudformation describe-stacks --stack-name glaedis-cognito-${TRAVIS_BRANCH} --query "Stacks[0].Outputs[?OutputKey=='CognitoUserPoolId'].OutputValue" --output text)
    - bash ./scripts/generate-env-front.sh
    if: branch = dev
    script:
    - cd frontend
    - npm install
    - npm run build
    - aws s3 cp ./dist s3://www.${DEV_DOMAIN}/ --recursive
env:
  global:
  - AWS_DEFAULT_REGION=eu-west-1
  - DOMAIN=glaedis.com
  - DEV_DOMAIN=dev.glaedis.com
  - EMAIL=simon.pichon@outlook.fr
  - secure: OFKl00OtZEN203RECSUWJEGwPNenMYqwRcH+M0RBAqZju5B4lsQqC2TRATNAadd8MdsKAWLl5C795EMH5z4K6PWgqUN/HcR0Xr/JZrw+OkYZURJEfjy1NIOict+5qB9XWCC4DZG+odCUkD1yA3o8SM+1x1cmbD0Qu1lMdk+I/PvaSwMnQFuPTYTpVkohMiPQ11EaZoQMJ8PNR5hEsoSrCKEufu9FQjMUiOU2RD2/Au8zLqj/GWLYGcOA3TBxK8rVzhxA7N3q5y20B3N7qKhBnXfJzWY70sI2/zP5O1B0wPc2Qot5GFhEdAKZKdRXjU1CvIy4t4SI3GiooAGtKtRSd/AxoNIOlfWUHmq78Q19KYeJONPhcRxwdw6WEjZ5C1Sqb3W/bdpDY8zYna+jhyzJX+PJN0VN+I/RiJMn1rGcVzQhVpMsb7nQY3BOIqXGK1xv0plhnpRHdANp/rIjtDdmP7bEsgpK2Fv2GsyTx4saVYiVDbfdclfPsDvXq6sVDO9H4baOa3zahpurh8IIeNBacFjCAJIxBVE2v1A/TnI9ePmFv63o8hqznwF6MkqFovfAvuJI3IE3qgCWDT7dsvEqFPAIC+xanbn++BYNnPca1ZR4Emxj3Z9GCxyJCKnMFxkucJg0xPBaBEdIcU36uIRXZfbw4Z3VbN7sJssFZHvXaH0=
  - secure: nnxqXIpeF6ggmA95s+firWjhYKlwqXBbEzpeZrpaOmjHmL1d9kjciubIVqFLdQrCXz/eLcvcFY0tHjGhClcoZS8yJ7sCbqedMSyGs+5jgOnYqm0e/Er5aH5/MpBruRo2LP+YgQdHuQyk7t0sKkQNhD71CuHkbZZ247l6lAf/SZ07MVLGmapZE4hpweCWHYjI3yNKoWnON0+pyI/QSc8wtnGQhB83CcgwOCq85LrGNcFczx4C/RPhIszrqrzbikBH+SdM1tRboK8jP8hn0mYkg4bXc6FKKqMtTEUggKMUTKdq/lntrwVVlhRFYcdtt64L9ez5eZvuORSK/UnjAmETRRN+XMQpJ2HdVaHZtTSiOJTkCsVrR/m2AHAEqkP4vgBmfcOQMMFMnrzXSrZlcUjYBkbaESO51G1fe5bNJF94Y1AxrtneaW+//umcSEjPE1K6Iq8aV/svbQvxYzevhnGWL/2h3LihRu4j0QeS3gf+3O+vsWtFDNPJnsnpZMCM5CT2oD2ye+G2Uj90G4j3JAAi3lU9eCKd5QjbusQLHYNijcb0h3jAQBXlzmYVc5r8hozbbc5lr9yQkfUA4GtiCdsST0IFQmk9dwdVATUIGAeyVUOGYUzKXliQc1lPp3QqcIQMI9zRKMCpmfiT5bqsBMP+6LtEFioTHRWkaDg5bwV8nvE=
  - secure: E7mEcpiBp8RPbPWmLLw3qBcciwQ4DqVaSw46xGhuVAuCB/O0XJd1ZG7nexexobHgScZ4DxIYUvM8pLxMKRHdOT1Rb1JinAiWJNER+hWRNdfkD6il/WOWOBekJlJ6cJSFUtN4gnzSqVl3ACjJ/UC1wPwoKvpabwegTh56I5Xp/1YNBjECeLiYE5erMMHaMsBPnf62WdcVZvm/Pl0YS/dkHyb2xkD2DwDGRzgCPRBrqoCmGMcv6HhtUFMB6yKq5ZcbgtI9+7wgyEpgCv0riJNIxlAErd6LLCh/MkwBkdOj/nX776Sv/Bi0eDNzmFO7fjWmb4PzB4GPw7qcPnnufIupLBu0gqV3W8AjVEbn5QZlgLfdkZR4aXT+h3QQPz2vvTni7VvZ4byJPaQbG+hZYQNC+96hD1i52Bg0SZUoKhzYOrU5UbcclfxWQIfmALCK764SsyLOrj/cgf+fxORewOpaq/6VjlptGAw/2ToIK9p71Pp/bBmF78ddpVnLr67Zzf+Nhn5bVF4oBoGCIPDqvsImwuMw1c95Monx7+0W6y6fvS4/rTdpVXEW3BYgP2WXJoubwDAt8Sc39POROxU04uzxLoW6uw4x5JyL+Vc0fkJpmzuLH5Ip3u9na1wmnaHqCzh3NFxcfjtDBXbaWNw0YWuH/oAtAiZ7HUxkYPD9X9FQ8RE=
  - secure: BbqmRuQgRhsntg1JiEj6Y3gbfRsa6BZfzhCfh0tBrEQ+EyGdnX7n91IjKp1OVIotq+v9kRJgoOorHHumb/c0qxz2dazEIhraEKw96TyZAtaJ8rCM/tzo6inOIGTZCADtAsjSoZLl38aB8mLLwxv1YkgHiwElx7IUo9X/X1HmEmxe93nRTlPuRcPMIJ3a8s3xnBzZKdnMS2DNWeSjVdFWl6MqAhj6xijWPvmg0+ich8Uy4JxKYLpH/Exv3++yHITZYMenYfDctiKFz6IX8a+MLmjoAZLtT/sVPADPS5n2j5uXMZVJmG84/7fzwR6jTcfeSOmtFl0DfSm+UNjR9miiSp5fYO0pYoOKOIftR/Hbf9ZMZY8aFiW487P5oaZWVe+wOvbqK9hO2fwBHn0VVWHw6leIJgMBkI9UUQNoW8Lb3gCVquzhrArTISo9yXXXwt60nV/Umh1BbCvP/lmoifHVALhFpawXqLW8VT3q8a6j7WlXJ0xGHA2zg+kXnsirUnnSx3m8/eczTwjPIu6ZjyEddRrGA7qxrhUoNXoUaLTKcztEArpceYpD4rJ6IVS/xMBFo5LJZGS812zPfNe7gGRDaUCm5rQHsxD4hs1xmyLYp77t+fezaxYx7DoorPq6hDrqEjpBhu8BHW7cfDgemDvU0RI1QV2sGPehjY00e103dkQ=
  - secure: IcsgsNHeuJvGyQ2zHIcvyVWkBqMfEq5FdN2KkfvMB3RxWbGV40HNv0gOgfblW09BCyFZvD8YcIFmlZp1Lc+WxHbNtHjANtuIKjPu2cx7G54DDZUHNqxOL+exr+SJ++mB5q6aPzOfltVBRZkVwe/LFCsMwXkrsp6nf1NQtXI8vz4ksWXwHJPeBaaRyNQItaXVSu+3jJsCs2rjCTGL4elZraRbYKBMKnVUrWn6uhaHuRdfZT5JnHvRUru2efQKFYdJvVEOtO+tHd3WzUq/I0JZjahRh7smuNDsNVBlEBcQ8RRmDubSQhnSGVKhF+CAmyEgX3Kyg9HcPAH0e5EieyluJ4NMt2UZQT6nt+Dx1dJztul2t11lxGVHrHcwv+o6Dn72z7mZLGn/dAn+SQsyMV0sLswk711MEMLPYy+axs7Jl551WJMbY0hOeVpk6pZRySGLH9NgaPiMo5UpWGleHrF5P5Hg7tdVLhhgUPzOuUAaaFMuEA1cis41koySXAx/qlrThUqmdSDEQLKEVSFXNF6ZjkVjEiLSKDis0/KfKgBY5UNH6cKLi+/wzw8NVBa+nEg8fsLZq3dVygH4Lt6P76BLox8DCSkKZN/FHpA27AcTurwgCGMvjmii5caApDdKWD5WCXIAPCT7AnYtom8NGe+V2iQ8zxIZs7MIC9tSvqkPw90=
  - secure: WVHdp/BAfW/vkCQTqsT0Nnk2UY1WMySEh+RK7Foh3iyDsq0yTm3Cn/xJxV02qKjh+ltA1yZglkLoRa5EqgBUa3vguG6U+lbMLkRovZ7uin47O6kCqDoIBvKLszd3VujdD/nFR6AYKhAhEFnla9OnOlJCTrCKvaJ1NN/aakezzzoi1s1Vj8oiX5xPKlR33EaGUFpzGShjef60ivxy4LTkaEJzTbaIm+7zUBQOq/15LRB8Z1NsSKpi3S55gUdJxA0xJc2LwhoUwk8sFN1ymgw1wGIdiyU2kbbhiHk/5JgROu3kX/B65VDTZRUmJjNPvf/qqCCBUuLgAHviBBhVJijSxdFCLG5/PSZng5ANMHetjMCtvgfFLzoVkxVhBiWVh6pZUSJ19E5EVfyWJAouMBZHv0Cp5oqe/ojNr80m0LJmHNDGvHnl3K0NkpXDx5+dEUrklYm0qwzliS+XVBJg2DS12ozF4yZs8gNmrOYRux6dkhEIV6tMgveHGygXMqonkSO7QT2OBdiF3/HDLyuKWxpFecvgeW84kOUxdY2Qfdp0Jfl0E30trF8rgWBPKetAxVQ33phYJZeqOPcmWNYLezy8HGaAm1yVfbz1y+rPitS4L/M6zdnFr9kTfVmLzfJvxJfdFoJYLLN8y31Ruuc/3LpTg9Th7nWB/GaWUn3ResZKmTg=
  - secure: J8gmdEpXTgjlZ3pDEP7VDmPYfx/F2QbjElCkOujplTWTdKC2gJv+xQtudtjf+BsQpyegPcqoTOzWifMYyQwDMdI0CVkuPyoqVK0mHRkIX/0rw8uwQ+Xsz3kiRVdE5iqrVzKCn7YwFRGh3lZwV4ev5S792x7Q/R8PKyGJEHs7JAvlwuN4HMmxlwtVVUf3SMB1TEbbT0RD+PMsImqQfjLrVNywd/mXO93cQkVU6T9AenJ3YIjRPYSNncUMdBx8tbrKSitIBnagq99P1LtObI6RSvnB0WT5mzscDCfZANxzZAMA+9Bq9XYlFy6lavVzAfR71kOa413xg1OcJP5BnlU6YVDTsHWeGbuip+s7VsgamIV4dvC8Nm1T7yNle99YxXzSGMCZPiEfM7LiXQ5n2ubPxklaXzTFW7z/TSx5CgtCho4lZiOI3YDS/UPT/9WdvGfgLs9178139VurVPkHCg1qIZ5AjfSWAyGDzbD99TCj06KtvwiyEZDbNHHqMlQUKFGuI2RFTk2rGsfZQEhwRBMnVqH66vWTheFeHoU2qZl9jerQiNl1AdEIoG1l1cWbT8IEH3NYxIng/R3/I5fx9EU6thr/C/rJ563VAHcaU7FcRN690azk6P0YpwA5117dTjLBGq0nmWHoXFs65/cfd9ghY/Sk0kE05YdkqVJqCiP9hnI=
  - secure: FEFww5vZjzRVu8ylq9a8iolNO7bYFuJGKqOAymmEq4rh6QcY8neHW2yZLjEH5GTOrcEVxsROQmg/hft4Lo/UChtuB+QW8XyABjud/4wI6kb0jrZgEWaUay35AiThWnJq2K3VNBCG6O8BNzTmWWzm4tJO62aVxNy3CD2ZtOBcZDmmNoL8rfkud78Gv7ptby2UmGCL1tghoN9qAHXtoTLtCVYGGXCCYeomsNaCiqyh90oiDE69zVuzIh6MsZJm47cWsZi3irbSjRMgyveqml71wqK6GKaX3no9flA5jlXIQyRQOnnXWpgmZyVNmfAuNKRLx2q/IeE14hqdcEMRQMQBIVk0ge9LllXZcLvUYz5lVSwXGgt9DuO3vTfHmVW4ug6KfKznQRAqCyAbiwHpWlHUrnYsiP78PnVAjr/sMabt+rUqwfphK0tu6czak0K+i7OKKGeiZh+SQUCWFMP5jg1XP50FtujasrGv2p/YEQEgMwwNmPSbptkLrC4flL00aYAHzQ5defen4RUV8jmmYa9+7sJtBeK9Lua7A+e1eAchVclerFdxZCmtVy+odSBpPiteB2yeA3f5YWkI4Vzb15sSD9hhw/cVq0Ms4uLar6FWandXfK/34OXUfIB3iQpidjN1M11O/VCRfTujVEb6O+B5bBJS0F3LTr8d1S+tDgk5yiU=
