version: '3.7'

services:
  backend:
    image: 'glaedis_backend:latest'
    build: backend/App
    container_name: backend
    volumes:
      - ./backend/App/:/App/
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8002:8000
    env_file:
      - .env
