"""add broker and account private status

Revision ID: 37b826c97024
Revises: 0b2c8c8986f3
Create Date: 2021-05-04 08:59:19.957072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b826c97024'
down_revision = '0b2c8c8986f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('broker_id', sa.String(), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broker_broker_id'), 'broker', ['broker_id'], unique=False)
    op.create_index(op.f('ix_broker_id'), 'broker', ['id'], unique=False)
    op.create_index(op.f('ix_broker_name'), 'broker', ['name'], unique=False)
    op.add_column('account', sa.Column('broker_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'account', 'broker', ['broker_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_column('account', 'broker_id')
    op.drop_index(op.f('ix_broker_name'), table_name='broker')
    op.drop_index(op.f('ix_broker_id'), table_name='broker')
    op.drop_index(op.f('ix_broker_broker_id'), table_name='broker')
    op.drop_table('broker')
    # ### end Alembic commands ###
