"""add date to transaction

Revision ID: a90078e45d18
Revises: c9520d2cc26c
Create Date: 2021-06-08 09:13:30.600349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a90078e45d18'
down_revision = 'c9520d2cc26c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'date')
    # ### end Alembic commands ###
