"""add array of tickers

Revision ID: f95b9eb86cc3
Revises: 29a772b79352
Create Date: 2021-05-23 10:45:00.982197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f95b9eb86cc3'
down_revision = '29a772b79352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broker', sa.Column('tickers', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broker', 'tickers')
    # ### end Alembic commands ###
