Description: Tables
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String

Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: "Id"
          AttributeType: "S"
        - AttributeName: "Key"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "Id"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "KeyLookup"
          KeySchema:
            - AttributeName: "Key"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
      TableName: !Sub
        - UserTable-${EnvironmentName}
        - { EnvironmentName: !Ref EnvironmentName }

Outputs:
  UserTableName:
    Description: "UserTableName"
    Value: !Ref UserTable
    Export:
      Name: !Sub
        - Glaedis-${EnvironmentName}-UserTableName
        - { EnvironmentName: !Ref EnvironmentName }

  UserTableArn:
    Description: "UserTableArn"
    Value: !GetAtt UserTable.Arn
    Export:
      Name: !Sub
        - Glaedis-${EnvironmentName}-UserTableArn
        - { EnvironmentName: !Ref EnvironmentName }
