Description: ALB And Lambdas
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub
                - www.${Domain}
                - Domain:
                    Fn::ImportValue:
                      !Sub
                      - Glaedis-${EnvironmentName}-RootDomain
                      - { EnvironmentName: !Ref EnvironmentName }
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
    DeletionPolicy: Retain
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: '*'
          Action: s3:GetObject
          Resource: !Join ['', ['arn:aws:s3:::', !Ref WebsiteBucket, /*]]
  WebsiteCloudfront:
    Type: AWS::CloudFront::Distribution
    DependsOn:
    - WebsiteBucket
    Properties:
      DistributionConfig:
        Comment: Cloudfront Distribution pointing to S3 bucket
        Origins:
        - DomainName: !Select [2, !Split ["/", !GetAtt WebsiteBucket.WebsiteURL]]
          Id: S3Origin
          CustomOriginConfig:
            HTTPPort: '80'
            HTTPSPort: '443'
            OriginProtocolPolicy: http-only
        Enabled: true
        HttpVersion: 'http2'
        DefaultRootObject: index.html
        Aliases:
          - !Sub
            - www.${Domain}
            - Domain:
                Fn::ImportValue:
                  !Sub
                  - Glaedis-${EnvironmentName}-RootDomain
                  - { EnvironmentName: !Ref EnvironmentName }
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          Compress: true
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn:
            Fn::ImportValue:
              !Sub
              - Glaedis-${EnvironmentName}-CloudFrontCertArn
              - { EnvironmentName: !Ref EnvironmentName }
          SslSupportMethod: sni-only

  WebsiteDNSName:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId:
        Fn::ImportValue:
          !Sub
          - Glaedis-${EnvironmentName}-HostedZoneId
          - { EnvironmentName: !Ref EnvironmentName }
      RecordSets:
      - Name: !Sub
          - www.${Domain}
          - Domain:
              Fn::ImportValue:
                !Sub
                - Glaedis-${EnvironmentName}-RootDomain
                - { EnvironmentName: !Ref EnvironmentName }
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt WebsiteCloudfront.DomainName
